USE coe_ecommerce;

-- ============================================================
-- CATEGORIES
-- ============================================================
INSERT INTO categories (name, slug, description) VALUES
  ('Prerana',             'prerana',             'Beautiful handcrafted products from Prerana community'),
  ('Shristi',             'shristi',             'Exquisite handcrafted products from Shristi community'),
  ('Bamboo',              'bamboo',              'Eco-friendly bamboo products'),
  ('Cotton Cushion Cover','cotton-cushion-cover', 'Handwoven cotton cushion covers'),
  ('Mekhela Sador',       'mekhela-sador',        'Traditional Assamese attire'),
  ('Cotton Stole',        'cotton-stole',         'Handwoven cotton stoles'),
  ('Eri Stole',           'eri-stole',            'Handwoven eri silk stoles'),
  ('Runner Set',          'runner-set',           'Table runner sets'),
  ('Mens Kurta',          'mens-kurta',           'Traditional mens kurta'),
  ('Yarn',                'yarn',                 'Naturally dyed yarn')
ON DUPLICATE KEY UPDATE
  name        = VALUES(name),
  description = VALUES(description);

-- ============================================================
-- PRERANA PRODUCTS (kebab-case filenames, no spaces)
-- ============================================================
INSERT INTO products (name, slug, description, price, stock, category_id, thumbnail_url, is_active) VALUES
('Cotton Cushion Cover',                 'prerana-cotton-cushion-cover',                 'Handwoven cotton cushion cover crafted by Prerana artisans using traditional techniques.',                           650.00, 10, (SELECT id FROM categories WHERE slug = 'prerana' LIMIT 1), '/assets/prerana/cotton-cushion-cover.jpg',                              1),
('Cotton Cushion Cover',                 'prerana-cotton-cushion-cover-2',               'Handwoven cotton cushion cover crafted by Prerana artisans using traditional techniques.',                           650.00, 10, (SELECT id FROM categories WHERE slug = 'prerana' LIMIT 1), '/assets/prerana/cotton-cushion-cover-2.jpg',                            1),
('Cotton Cushion Cover',                 'prerana-cotton-cushion-cover-3',               'Handwoven cotton cushion cover crafted by Prerana artisans using traditional techniques.',                           650.00, 10, (SELECT id FROM categories WHERE slug = 'prerana' LIMIT 1), '/assets/prerana/cotton-cushion-cover-3.jpg',                            1),
('Natural Dye Cushion Cover',            'prerana-natural-dye-cushion-cover',            'Beautiful cushion cover dyed using natural pigments — earthy tones that are eco-friendly and unique.',             750.00,  8, (SELECT id FROM categories WHERE slug = 'prerana' LIMIT 1), '/assets/prerana/Natural-dye-cushion-cover.jpg',                         1),
('Cotton Mekhela Sador',                 'prerana-cotton-mekhela-sador',                 'Traditional Assamese two-piece attire (Mekhela Sador) handwoven in pure cotton by Prerana weavers.',            3200.00,  5, (SELECT id FROM categories WHERE slug = 'prerana' LIMIT 1), '/assets/prerana/cotton-mekhela-sador.jpg',                              1),
('Cotton Mekhela Sador',                 'prerana-cotton-mekhela-sador-full',            'Traditional Assamese Mekhela Sador — handwoven full-length cotton with elegant drape.',                          3500.00,  5, (SELECT id FROM categories WHERE slug = 'prerana' LIMIT 1), '/assets/prerana/cotton-mekhela-sador-full.jpg',                         1),
('Cotton Mekhela Sador (Henna Dyed)',    'prerana-cotton-mekhela-sador-henna',           'Naturally dyed with henna, this handwoven Mekhela Sador has a soft golden-green earthy tone.',                  3800.00,  4, (SELECT id FROM categories WHERE slug = 'prerana' LIMIT 1), '/assets/prerana/cotton-mekhela-sador-naturally-dyed-with-henna.jpg',    1),
('Natural Dye Cotton-Eri Mekhela Sador', 'prerana-natural-dye-cotton-eri-mekhela-sador', 'Exquisite Mekhela Sador blending cotton and eri silk, dyed using natural plant-based pigments.',             4200.00,  4, (SELECT id FROM categories WHERE slug = 'prerana' LIMIT 1), '/assets/prerana/Natural-dye-Cotton-eri-mekhela-sador.jpg',              1),
('Cotton Stole',                         'prerana-cotton-stole',                         'Handwoven cotton stole in earthy natural tones — lightweight, breathable and elegant.',                            900.00, 12, (SELECT id FROM categories WHERE slug = 'prerana' LIMIT 1), '/assets/prerana/Cotton-stole.jpg',                                      1),
('Cotton Stole',                         'prerana-cotton-stole-2',                       'Handwoven cotton stole featuring subtle natural dye patterns — perfect everyday accessory.',                       950.00, 12, (SELECT id FROM categories WHERE slug = 'prerana' LIMIT 1), '/assets/prerana/cotton-stole-2.jpg',                                    1),
('Eri Stole',                            'prerana-eri-stole',                            'Luxuriously soft eri silk stole handwoven by Prerana artisans — warm, breathable and sustainable.',              1400.00,  8, (SELECT id FROM categories WHERE slug = 'prerana' LIMIT 1), '/assets/prerana/eri-stole.jpg',                                         1),
('Eri Stole',                            'prerana-eri-stole-2',                          'Handwoven eri silk stole with delicate texture — a timeless sustainable fashion accessory.',                      1450.00,  8, (SELECT id FROM categories WHERE slug = 'prerana' LIMIT 1), '/assets/prerana/eri-stole-2.jpg',                                       1),
('Eri Stole (Close-up)',                 'prerana-eri-stole-closeup',                    'Premium handwoven eri stole showcasing intricate weave detail and natural silk sheen.',                           1500.00,  6, (SELECT id FROM categories WHERE slug = 'prerana' LIMIT 1), '/assets/prerana/eri-stole-close-up-1.jpg',                              1),
('Eri Stole (Full)',                     'prerana-eri-stole-full',                       'Full-length eri silk stole — soft, warm and crafted with care by Prerana weavers.',                              1550.00,  6, (SELECT id FROM categories WHERE slug = 'prerana' LIMIT 1), '/assets/prerana/eri-stole-full.jpg',                                    1),
('Naturally Dyed Eri Yarn',              'prerana-natural-dye-eri-yarn',                 'Hand-spun eri silk yarn dyed with natural plant extracts — available for crafters and weavers.',                  600.00, 15, (SELECT id FROM categories WHERE slug = 'prerana' LIMIT 1), '/assets/prerana/naturally-dyed-eri-yarn.jpg',                           1),
('Runner Set (Cotton)',                  'prerana-runner-set-cotton',                    'Handwoven cotton runner set — perfect for dining tables, showcasing traditional Assamese weaving.',               1800.00,  8, (SELECT id FROM categories WHERE slug = 'prerana' LIMIT 1), '/assets/prerana/runner-set-cotton-1.jpg',                               1),
('Runner Set (Cotton)',                  'prerana-runner-set-cotton-2',                  'Elegant handwoven cotton table runner set with intricate pattern detailing.',                                     1800.00,  8, (SELECT id FROM categories WHERE slug = 'prerana' LIMIT 1), '/assets/prerana/runner-set-cotton-2.jpg',                               1),
('Runner Set (Cotton)',                  'prerana-runner-set-cotton-3',                  'Handwoven cotton runner set crafted in soft neutral tones for any dining aesthetic.',                             1750.00, 10, (SELECT id FROM categories WHERE slug = 'prerana' LIMIT 1), '/assets/prerana/Runner-set-cotton-3.jpg',                               1),
('Runner Set (Cotton)',                  'prerana-runner-set-cotton-4',                  'Beautiful cotton table runner with traditional motifs, handcrafted by Prerana weavers.',                          1750.00, 10, (SELECT id FROM categories WHERE slug = 'prerana' LIMIT 1), '/assets/prerana/runner-set-cotton-4.jpg',                               1),
('Runner Set (Cotton)',                  'prerana-runner-set-cotton-5',                  'Handloom cotton runner set — adds a natural, artisanal touch to your table setting.',                            1800.00,  8, (SELECT id FROM categories WHERE slug = 'prerana' LIMIT 1), '/assets/prerana/runner-set-cotton-5.jpg',                               1),
('Runner Set (Cotton)',                  'prerana-runner-set-cotton-6',                  'Sustainably woven cotton runner set with rich texture and traditional Assamese design.',                          1800.00,  8, (SELECT id FROM categories WHERE slug = 'prerana' LIMIT 1), '/assets/prerana/runner-set-cotton-6.jpg',                               1),
('Runner Set (Cotton)',                  'prerana-runner-set-cotton-7',                  'Handwoven cotton runner — lightweight and easy-care with beautiful woven details.',                               1750.00, 10, (SELECT id FROM categories WHERE slug = 'prerana' LIMIT 1), '/assets/prerana/runner-set-cotton-7.jpg',                               1),
('Runner Set (Cotton)',                  'prerana-runner-set-cotton-8',                  'Elegant handwoven cotton runner set — a statement piece for any dining table.',                                  1750.00, 10, (SELECT id FROM categories WHERE slug = 'prerana' LIMIT 1), '/assets/prerana/runner-set-cotton-8.jpg',                               1),
('Tie and Dye Men\'s Kurta',            'prerana-tie-dye-mens-kurta',                   'Handcrafted tie and dye kurta for men — each piece uniquely patterned with vibrant natural dyes.',               1600.00,  6, (SELECT id FROM categories WHERE slug = 'prerana' LIMIT 1), '/assets/prerana/tie-and-dye-mens-kurta.jpg',                            1),
('Handcrafted Textile',                  'prerana-handcrafted-textile-1',                'Handcrafted textile product from the Prerana women\'s artisan collective.',                                        800.00, 10, (SELECT id FROM categories WHERE slug = 'prerana' LIMIT 1), '/assets/prerana/IMG-20260129-WA0008.jpg',                                1),
('Handcrafted Textile',                  'prerana-handcrafted-textile-2',                'Handcrafted textile product from the Prerana women\'s artisan collective.',                                        800.00, 10, (SELECT id FROM categories WHERE slug = 'prerana' LIMIT 1), '/assets/prerana/IMG-20260129-WA0018.jpg',                                1),
('Handcrafted Textile',                  'prerana-handcrafted-textile-3',                'Handcrafted textile product from the Prerana women\'s artisan collective.',                                        800.00, 10, (SELECT id FROM categories WHERE slug = 'prerana' LIMIT 1), '/assets/prerana/IMG-20260129-WA0021.jpg',                                1),
('Handcrafted Textile',                  'prerana-handcrafted-textile-4',                'Handcrafted textile product from the Prerana women\'s artisan collective.',                                        800.00, 10, (SELECT id FROM categories WHERE slug = 'prerana' LIMIT 1), '/assets/prerana/IMG-20260129-WA0022.jpg',                                1),
('Handcrafted Textile',                  'prerana-handcrafted-textile-5',                'Handcrafted textile product from the Prerana women\'s artisan collective.',                                        800.00, 10, (SELECT id FROM categories WHERE slug = 'prerana' LIMIT 1), '/assets/prerana/IMG-20260129-WA0025.jpg',                                1),
('Handcrafted Textile',                  'prerana-handcrafted-textile-6',                'Handcrafted textile product from the Prerana women\'s artisan collective.',                                        800.00, 10, (SELECT id FROM categories WHERE slug = 'prerana' LIMIT 1), '/assets/prerana/IMG-20260129-WA0027.jpg',                                1)
ON DUPLICATE KEY UPDATE
  description   = VALUES(description),
  price         = VALUES(price),
  stock         = VALUES(stock),
  thumbnail_url = VALUES(thumbnail_url),
  is_active     = VALUES(is_active);

-- ============================================================
-- SHRISTI PRODUCTS (kebab-case filenames, no spaces)
-- ============================================================
INSERT INTO products (name, slug, description, price, stock, category_id, thumbnail_url, is_active) VALUES
('Hand Bag',                             'shristi-hand-bag',                     'Handcrafted bag from the Shristi women\'s collective — durable, stylish and sustainably made.',          950.00,  8, (SELECT id FROM categories WHERE slug = 'shristi' LIMIT 1), '/assets/shristi/hand-bag.jpeg',                          1),
('Small Hand Bag',                       'shristi-small-hand-bag',               'Compact handcrafted bag by Shristi artisans — perfect everyday carry in a sustainable design.',           750.00, 10, (SELECT id FROM categories WHERE slug = 'shristi' LIMIT 1), '/assets/shristi/small-handbag.jpeg',                     1),
('Bamboo Tray',                          'shristi-bamboo-tray',                  'Handcrafted bamboo tray — lightweight, eco-friendly and beautifully finished.',                           650.00, 12, (SELECT id FROM categories WHERE slug = 'shristi' LIMIT 1), '/assets/shristi/bamboo-tray.jpeg',                       1),
('Round Tray',                           'shristi-round-tray',                   'Elegant round handwoven tray from Shristi collective — versatile for serving or display.',                700.00, 10, (SELECT id FROM categories WHERE slug = 'shristi' LIMIT 1), '/assets/shristi/round-tray.jpeg',                        1),
('Bamboo Coaster',                       'shristi-bamboo-coaster',               'Set of handcrafted bamboo coasters — natural, sturdy and eco-friendly.',                                  350.00, 20, (SELECT id FROM categories WHERE slug = 'shristi' LIMIT 1), '/assets/shristi/bamboo-coster.jpeg',                     1),
('Water Hyacinth Place Mat',             'shristi-water-hyacinth-place-mat',     'Handwoven water hyacinth place mat — adds a natural, earthy charm to your dining table.',                480.00, 15, (SELECT id FROM categories WHERE slug = 'shristi' LIMIT 1), '/assets/shristi/Place-mat.jpeg',                         1),
('Water Hyacinth Place Mat',             'shristi-water-hyacinth-place-mat-2',   'Beautifully handwoven water hyacinth place mat — sustainable and stylish dining accessory.',             480.00, 15, (SELECT id FROM categories WHERE slug = 'shristi' LIMIT 1), '/assets/shristi/water-hyacinth-placemat-2.jpeg',         1),
('Table Mat',                            'shristi-table-mat',                    'Handcrafted table mat from Shristi collective — natural fibers woven into a durable, beautiful mat.',    450.00, 15, (SELECT id FROM categories WHERE slug = 'shristi' LIMIT 1), '/assets/shristi/table-mat.jpeg',                         1),
('Runner Set (Cotton & Water Hyacinth)', 'shristi-runner-set-cotton-hyacinth',   'Unique table runner set blending cotton and water hyacinth — handwoven by Shristi artisans.',           1900.00,  8, (SELECT id FROM categories WHERE slug = 'shristi' LIMIT 1), '/assets/shristi/runner-set-cotton-water-hyacinth.jpeg',  1),
('Runner Set (Cotton & Water Hyacinth)', 'shristi-runner-set-cotton-hyacinth-2', 'Handwoven cotton and water hyacinth runner set — an elegant sustainable centerpiece.',                  1900.00,  8, (SELECT id FROM categories WHERE slug = 'shristi' LIMIT 1), '/assets/shristi/runner-set-cotton-water-hyacinth-2.jpeg',1),
('Cushion Cover',                        'shristi-cushion-cover',                'Handwoven cushion cover from Shristi collective — adds artisanal warmth to any living space.',           700.00, 12, (SELECT id FROM categories WHERE slug = 'shristi' LIMIT 1), '/assets/shristi/cushion-cover.jpeg',                     1),
('Napkin Holder',                        'shristi-napkin-holder',                'Handcrafted napkin holder — a practical and stylish addition to your dining table.',                      400.00, 15, (SELECT id FROM categories WHERE slug = 'shristi' LIMIT 1), '/assets/shristi/napkin-holder.jpeg',                     1),
('Small Planter',                        'shristi-small-planter',                'Handwoven small planter — a beautiful eco-friendly home for your indoor plants.',                         550.00, 12, (SELECT id FROM categories WHERE slug = 'shristi' LIMIT 1), '/assets/shristi/small-planter.jpeg',                     1),
('Medium Planter',                       'shristi-medium-planter',               'Handwoven medium planter by Shristi artisans — natural and stylish home decor.',                         750.00, 10, (SELECT id FROM categories WHERE slug = 'shristi' LIMIT 1), '/assets/shristi/planter-medium.jpeg',                    1),
('Flower Vase',                          'shristi-flower-vase',                  'Handcrafted flower vase from Shristi — a beautiful, sustainable piece for home decoration.',              600.00, 10, (SELECT id FROM categories WHERE slug = 'shristi' LIMIT 1), '/assets/shristi/flower-vase.jpeg',                       1),
('Handcrafted Product',                  'shristi-handcrafted-1',                'Handcrafted product from the Shristi women\'s collective.',                                                700.00,  8, (SELECT id FROM categories WHERE slug = 'shristi' LIMIT 1), '/assets/shristi/IMG_3875.jpeg',                          1),
('Handcrafted Product',                  'shristi-handcrafted-2',                'Handcrafted product from the Shristi women\'s collective.',                                                700.00,  8, (SELECT id FROM categories WHERE slug = 'shristi' LIMIT 1), '/assets/shristi/IMG_3876.jpeg',                          1),
('Handcrafted Product',                  'shristi-handcrafted-3',                'Handcrafted product from the Shristi women\'s collective.',                                                700.00,  8, (SELECT id FROM categories WHERE slug = 'shristi' LIMIT 1), '/assets/shristi/IMG_3877.jpeg',                          1),
('Handcrafted Product',                  'shristi-handcrafted-4',                'Handcrafted product from the Shristi women\'s collective.',                                                700.00,  8, (SELECT id FROM categories WHERE slug = 'shristi' LIMIT 1), '/assets/shristi/IMG_4401.jpeg',                          1)
ON DUPLICATE KEY UPDATE
  description   = VALUES(description),
  price         = VALUES(price),
  stock         = VALUES(stock),
  thumbnail_url = VALUES(thumbnail_url),
  is_active     = VALUES(is_active);

-- ============================================================
-- BAMBOO PRODUCTS (kebab-case filenames, no spaces)
-- ============================================================
INSERT INTO products (name, slug, description, price, stock, category_id, thumbnail_url, is_active) VALUES
('Bamboo Bag',          'bamboo-bag',           'Eco-friendly bamboo bag crafted by artisans — stylish, durable and sustainably made.',                    950.00, 10, (SELECT id FROM categories WHERE slug = 'bamboo' LIMIT 1), '/assets/bamboo/bamboo-bag.jpg',           1),
('Bamboo Bag',          'bamboo-bag-2',         'Eco-friendly bamboo bag — a unique sustainable fashion accessory handcrafted with care.',                  900.00, 10, (SELECT id FROM categories WHERE slug = 'bamboo' LIMIT 1), '/assets/bamboo/bamboo-bag-2.jpg',         1),
('Bamboo Box',          'bamboo-box',           'Handcrafted bamboo box — perfect for storage or gifting, beautifully finished.',                           750.00, 12, (SELECT id FROM categories WHERE slug = 'bamboo' LIMIT 1), '/assets/bamboo/bamboo-box.jpg',           1),
('Bamboo File Cover',   'bamboo-file-cover',    'Elegant bamboo file cover — eco-friendly and professionally crafted for everyday use.',                    850.00,  8, (SELECT id FROM categories WHERE slug = 'bamboo' LIMIT 1), '/assets/bamboo/bamboo-file-cover.png',    1),
('Bamboo Lamp Stand',   'bamboo-lamp-stand',    'Handcrafted bamboo lamp stand — adds a natural, warm aesthetic to any room.',                            1200.00,  6, (SELECT id FROM categories WHERE slug = 'bamboo' LIMIT 1), '/assets/bamboo/bamboo-lamp-stand.jpg',    1),
('Bamboo Mat Purse',    'bamboo-mat-purse',     'Stylish bamboo mat purse — a unique eco-friendly accessory for everyday carry.',                           800.00, 10, (SELECT id FROM categories WHERE slug = 'bamboo' LIMIT 1), '/assets/bamboo/bamboo-mat-purse.jpg',     1),
('Bamboo Mat Tray',     'bamboo-mat-tray',      'Handwoven bamboo mat tray — lightweight and perfect for serving or display.',                              650.00, 12, (SELECT id FROM categories WHERE slug = 'bamboo' LIMIT 1), '/assets/bamboo/bamboo-mat-tray.jpg',      1),
('Bamboo Pen Stand',    'bamboo-pen-stand',     'Handcrafted bamboo pen stand — a sustainable and stylish addition to any desk.',                           450.00, 15, (SELECT id FROM categories WHERE slug = 'bamboo' LIMIT 1), '/assets/bamboo/bamboo-pen-stand.jpg',     1),
('Bamboo Tray',         'bamboo-tray',          'Elegant handcrafted bamboo tray — versatile for serving, storage or home decor.',                          700.00, 12, (SELECT id FROM categories WHERE slug = 'bamboo' LIMIT 1), '/assets/bamboo/bamboo-tray.png',          1),
('Bamboo Tray',         'bamboo-tray-3',        'Beautifully crafted bamboo tray with natural finish — a sustainable home essential.',                      680.00, 12, (SELECT id FROM categories WHERE slug = 'bamboo' LIMIT 1), '/assets/bamboo/bamboo-tray-3.png',        1),
('Bamboo Yoga Mat',     'bamboo-yoga-mat',      'Natural bamboo yoga mat — eco-friendly, non-slip and perfect for your practice.',                         1500.00,  8, (SELECT id FROM categories WHERE slug = 'bamboo' LIMIT 1), '/assets/bamboo/bamboo-yoga-mat.jpg',      1),
('Jewellery Box',       'bamboo-jewellary-box', 'Handcrafted bamboo jewellery box — beautifully finished and perfect for gifting.',                         950.00,  8, (SELECT id FROM categories WHERE slug = 'bamboo' LIMIT 1), '/assets/bamboo/jewellary-box.png',        1),
('Laundry Basket',      'bamboo-laundry-basket','Sturdy handwoven bamboo laundry basket — eco-friendly and spacious.',                                     1100.00,  6, (SELECT id FROM categories WHERE slug = 'bamboo' LIMIT 1), '/assets/bamboo/laundry-basket.jpg',       1),
('Laundry Basket',      'bamboo-laundry-basket-1','Handcrafted bamboo laundry basket — natural, durable and beautifully woven.',                          1050.00,  6, (SELECT id FROM categories WHERE slug = 'bamboo' LIMIT 1), '/assets/bamboo/laundry-basket-1.jpg',     1),
('Napkin Holder',       'bamboo-napkin-holder', 'Handcrafted bamboo napkin holder — a practical and stylish dining accessory.',                             400.00, 15, (SELECT id FROM categories WHERE slug = 'bamboo' LIMIT 1), '/assets/bamboo/napkin-holder.jpg',        1),
('Napkin Holder',       'bamboo-napkin-holder-2','Bamboo napkin holder with elegant natural finish — adds charm to any dining table.',                      420.00, 15, (SELECT id FROM categories WHERE slug = 'bamboo' LIMIT 1), '/assets/bamboo/napkin-holder2.jpg',       1),
('Storage Basket',      'bamboo-storage-basket-2','Handwoven bamboo storage basket — strong, eco-friendly and beautifully crafted.',                        850.00, 10, (SELECT id FROM categories WHERE slug = 'bamboo' LIMIT 1), '/assets/bamboo/storage-basket-2.jpg',     1),
('Storage Basket',      'bamboo-storage-basket-4','Large handwoven bamboo storage basket — perfect for organizing any space sustainably.',                  900.00, 10, (SELECT id FROM categories WHERE slug = 'bamboo' LIMIT 1), '/assets/bamboo/storage-basket-4.jpg',     1),
('Yoga Mat',            'bamboo-yoga-mat-natural','Natural fiber yoga mat — eco-conscious and comfortable for all types of practice.',                     1400.00,  8, (SELECT id FROM categories WHERE slug = 'bamboo' LIMIT 1), '/assets/bamboo/yoga-mat.jpg',             1)
ON DUPLICATE KEY UPDATE
  description   = VALUES(description),
  price         = VALUES(price),
  stock         = VALUES(stock),
  thumbnail_url = VALUES(thumbnail_url),
  is_active     = VALUES(is_active);